# Generated by Django 5.2.7 on 2025-10-22 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.TextField(verbose_name='Pregunta')),
                ('reverso', models.TextField(verbose_name='Respuesta')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('aprendizaje', 'Aprendizaje'), ('consolidacion', 'Consolidación'), ('maduro', 'Maduro')], default='nuevo', max_length=20)),
                ('fase', models.IntegerField(choices=[(1, 'Fase 1 - Aprendizaje Intensivo'), (2, 'Fase 2 - Consolidación'), (3, 'Fase 3 - Mantenimiento')], default=1)),
                ('intervalo_actual', models.FloatField(default=5.0, help_text='Intervalo en segundos')),
                ('EF', models.FloatField(default=2.5, verbose_name='Factor de Facilidad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_repeticion', models.DateTimeField(blank=True, null=True)),
                ('siguiente_repeticion', models.DateTimeField(default=django.utils.timezone.now)),
                ('contador_aciertos', models.IntegerField(default=0)),
                ('contador_fallos', models.IntegerField(default=0)),
                ('tiempo_respuesta', models.FloatField(default=0.0, help_text='Tiempo en segundos')),
                ('calificacion_ajustada', models.FloatField(default=0.0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['siguiente_repeticion'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('calificacion_base', models.IntegerField(help_text='Calificación 0-5 del usuario')),
                ('tiempo_respuesta', models.FloatField(help_text='Tiempo en segundos')),
                ('calificacion_ajustada', models.FloatField(help_text='Calificación ajustada por tiempo')),
                ('fase_antes', models.IntegerField()),
                ('fase_despues', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flashcards.card')),
            ],
            options={
                'verbose_name': 'Registro de Revisión',
                'verbose_name_plural': 'Registros de Revisiones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField(verbose_name='Clave P256DH')),
                ('auth', models.TextField(verbose_name='Clave Auth')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción a Notificaciones',
                'verbose_name_plural': 'Suscripciones a Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tarjetas_nuevas_diarias', models.IntegerField(default=10)),
                ('tarjetas_nuevas_hoy', models.IntegerField(default=0)),
                ('ultima_fecha_reset', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
            },
        ),
    ]
