# Generated by Django 5.2.7 on 2025-10-22 21:11

import flashcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='ultima_fecha_reset',
            field=models.DateField(default=flashcards.models.get_fecha_hoy),
        ),
    ]
